#
# Copyright (c) 2017-present Paul Borza
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#

image: node:latest

build:
    stage: build
    script:
        - npm install -g grunt-cli
        - npm install
        - grunt
        - sed -i .bak "s/\"version\": \"\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)\"/\"version\": \"\1.\2\.`date '+%Y%m%d'`\"/g" package.json
        - npm publish
